// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char THING_ID[]           = "THING_IDTHING_IDTHING_ID";
const char DEVICE_LOGIN_NAME[]  = "DEVICE_LOGIN_NAMEDEVICE_LOGIN_NAMEDEVICE_LOGIN_NAME";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRefreshTimeChange();

#ifndef STASSID
#define STASSID "STASSID"
#define STAPSK  "STAPSK"
#endif
String cloudip = "0.0.0.0";
String wanip = "0.0.0.0";
String localip="0.0.0.0";
int refreshTime= 60000;
String CFKEY = "CFKEYCFKEYCFKEYCFKEYCFKEYCFKEYCFKEYCFKEY";
String CFUSER = "CFUSERCFUSERCFUSERCFUSER";
String CFZONE_NAME = "CFZONE_NAME CFZONE_NAME";
String CFRECORD_NAME = "CFRECORD_NAME CFRECORD_NAME";
String CFRECORD_TYPE = "A";
String CFZONE_ID = "";
String CFRECORD_ID = "";
String CFTTL = "120";
String IPCheckAddress = "http://ipv4.icanhazip.com";
const char* wifissid = STASSID;
const char* wifipassword = STAPSK;
long unsigned int  lastrefreshtime = 0;
const int wifiPin = 0;
const int netPin = 2;
bool ledState = 0;
const uint8_t fingerprint[20] = {0x40, 0xaf, 0x00, 0x6b, 0xec, 0x90, 0x22, 0x41, 0x8e, 0xa3, 0xad, 0xfa, 0x1a, 0xe8, 0x25, 0x41, 0x1d, 0x1a, 0x54, 0xb3};
ESP8266WebServer wwwserver(80);
WiFiUDP UDP; 
WakeOnLan WOL(UDP);
ESP8266WiFiMulti WiFiMulti;
String MACAddress = "MACAddressMACAddress";

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(cloudip, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(wanip, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(refreshTime, READWRITE, 60 * SECONDS, onRefreshTimeChange);
  ArduinoCloud.addProperty(CFRECORD_NAME, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(localip, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(CFRECORD_TYPE, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(CFZONE_NAME, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(CFZONE_ID, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(CFRECORD_ID, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(CFTTL, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(IPCheckAddress, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(MACAddress, READWRITE, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
